app/models.py
from flask_sqlalchemy import SQLAlchemy

db = SQLAlchemy()

class User(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(80), unique=True, nullable=False)

app/Hello/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField
from wtforms.validators import DataRequired, Email

class UserForm(FlaskForm):
    username = StringField('Nome do sócio', validators=[DataRequired(message='O nome é obrigatório')])
    submit = SubmitField()
    

app/Hello/routes.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from ..models import User, db
from .forms import UserForm

hello_bp = Blueprint('hello', __name__)

@hello_bp.route('/')
def index():
    users = User.query.all()
    form = UserForm()
    return render_template('index.html', users=users, form=form)

@hello_bp.route('/newUser', methods=['POST'])
def newUser():
    form = UserForm()
    if form.validate_on_submit():
        username = form.username.data

        newUser = User(username=username)
        db.session.add(newUser)
        db.session.commit()
        flash('Usuário criado com sucesso!', 'success')
    else:
        for field, errors in form.errors.items():
            for error in errors:
                flash(f'Erro no campo ({getattr(form,field).label.text}): {error}', 'danger')

    return redirect(url_for('hello.index'))

@hello_bp.route('/deleteUser/<int:userId>', methods=['POST'])
def deleteUser(userId):
    user = User.query.get_or_404(userId)

    if user:
        db.session.delete(user)
        db.session.commit()
        flash('Usuário removido com sucesso!', 'success')
    
    return redirect(url_for('hello.index'))

@hello_bp.route('/editUser/<int:userId>', methods=['POST'])
def editUser(userId):
    user = User.query.get_or_404(userId)
    form = UserForm()
    if form.validate_on_submit():
        user.username = form.username.data
        db.session.commit()
        flash('Usuário atualizado com sucesso!', 'success')

    return redirect(url_for('hello.index'))



@hello_bp.route('/sobre')
def about():
    return "Olá, Gremista nato!"

app/__init__.py
from flask import *
from .Hello.routes import hello_bp
from .models import db
import os

def create_app():
    app = Flask(__name__)
    app.secret_key = os.getenv('SECRET_KEY')
    app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///test.db'
    app.register_blueprint(hello_bp)
    db.init_app(app)
    with app.app_context():
        db.create_all()

    return app

app/templates/index.html
<!--  Mateus Gustavo Haupt -->
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}">
    
    <title>Hello</title>
</head>
<body>
    <div class="div-main">
        <h1>Dale Grêmio!</h1>

        {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
                {% for category, messages in messages %}
                    <div class="alert alert-{{category}}">{{message}}</div>
                {% endfor %}
            {% endif %}
        {% endwith %}

        <div class="div-card">
            <h1>Criar sócio do grêmio</h1>
            
            
            
            <form action="{{url_for('hello.newUser')}}" method="POST" novalidate> 
                {{ form.hidden_tag() }}
                {{ form.username.label }}
                {{ form.username(class="form-control", placeholder="Nome") }}
                {{ form.submit(class="btn-submit", value="Criar") }}
                <!--
                <div class="div-field">
                    <label for="username">Nome</label>
                    <input type="text" id="username" name="username" required>    
                </div>
                
                <button type="submit">Cadastrar</button>
                -->
            </form>
        </div>
        
        <div class="div-card">
            <h1>Gremistas fiéis</h1>
            <div class="div-main">
                {% for user in users %}
                <div class="div-list">
                    <p>{{ loop.index }} - </p>
                    <form action="{{url_for('hello.editUser', userId=user.id)}}" method="POST" novalidate>
                        
                        {{ form.hidden_tag() }}
                        {{ form.username(class="form-control", placeholder="Nome", value=user.username) }}
                        {{ form.submit(class="btn-submit", value="Atualizar") }}
                    </form>
                    <form action="{{url_for('hello.deleteUser', userId=user.id)}}" method="POST" novalidate>
                        <button type="submit">Remover</button>
                    </form>
                </div>
                    
                {% endfor %}
            </div>
        </div>
        
        <div class="div-card">
            <h1>O gremista mais fiel</h1>
            <div>
                <img class="profile-image" src="https://pm1.aminoapps.com/8239/6a51670b2a120c6fc476d47de94c46a633445d66r1-637-618v2_hq.jpg" alt="zoro">
            </div>
        </div>
    </div>
    

    <script src="{{ url_for('static', filename='js/scripts.js') }}"></script>
    
</body>
</html>